name: dio_mocked_response_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  rxdart: ^0.28.0
  go_router: ^17.0.0
  get_it: ^9.0.5
  injectable: ^2.6.0
  flutter_bloc: ^9.1.1
  oauth2: ^2.0.5
  localstorage: ^6.0.0
  openid_client: ^0.4.9+1
  dio: ^5.9.0
  url_launcher: ^6.3.2
  retrofit: ^4.9.0
  logger: ^2.6.2
  json_annotation: ^4.9.0
  flavor: ^2.0.0
  universal_platform: ^1.1.0
  clock: ^1.1.2
  intl: ^0.20.2
  autoscale_tabbarview: ^1.0.2
  flutter_svg: ^2.2.2
  characters: ^1.4.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  hive: ^2.2.3
  freezed_annotation: ^3.1.0
  flutter_animate: ^4.5.2
  youtube_player_flutter_plus: ^9.0.0
  youtube_player_iframe: ^5.2.2
  http_parser: ^4.1.2
  file_picker: ^10.3.6
  fl_chart: ^1.1.1
  skeletonizer: ^2.1.0+1
  dio_oidc_interceptor: ^1.2.4
  dio_mocked_responses:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.2
  injectable_generator: ^2.9.1
  retrofit_generator: ^10.0.6
  json_serializable: ^6.11.1
  bdd_widget_test: ^2.1.3
  freezed: ^3.2.3

flutter:
  uses-material-design: true
