name: dio_mocked_responses
description: Interceptor that help you to mock backend responses in flutter project.
version: 1.6.5+1
homepage: https://listo.pro
repository: https://github.com/b-fontaine/dio_mocked_responses

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  template_expressions_4: ^4.0.0+2
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

workspace:
  - example


flutter:
